/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    // tests not end, it is need to configure, that just initial tests

    @Test
    public boolean waterMark() {
        assertTrue(waterMark(), "This will succeed.");
        return false;
    }

    @Test
    public void NegativeColor() {
        assertTrue(true, "This will succeed.");
    }

    @Test
    public void grey() {
        assertTrue(true, "This will succeed.");
    }

    @Test
    public void reverseImageVertically() {
        assertTrue(true, "This will succeed.");
    }

    @Test
    public void reverseImageHorizontally() {
        assertTrue(true, "This will succeed.");
    }

}
