/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.util.Scanner;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        Scanner sc = new Scanner(System.in); // Create a Scanner object
        System.out.println(
                "Choose the number from the list to make a change to the image to be: \n 1: Negative colors \n 2: Grey color \n 3: Reverse Vertical \n 4: Reverse Horizantal \n 5: Add watermark ");
        String number = sc.nextLine();
        String inputFilePathToImage = "./app/src/main/resources/blue-bird.bmp";
        String outputFilePathToFolder = "./app/src/main/resources/newImages/";

        Bitmap process;

        switch (Integer.parseInt(number)) {
            case 1:
                System.out.println("The image become negative");
                process = new Bitmap(inputFilePathToImage, outputFilePathToFolder, "negative.bmp");

                process.NegativeColor();
                sc.close();

                break;
            case 2:
                System.out.println("The image become grey");
                process = new Bitmap(inputFilePathToImage, outputFilePathToFolder, "grey.bmp");

                process.grey();
                sc.close();
                break;
            case 3:
                System.out.println("The image reversed vertical");
                process = new Bitmap(inputFilePathToImage, outputFilePathToFolder, "vertical.bmp");

                process.reverseImageVertically();
                sc.close();
                break;
            case 4:
                System.out.println("The image reversed Horizontal");
                process = new Bitmap(inputFilePathToImage, outputFilePathToFolder, "Horizontal.bmp");

                process.reverseImageHorizontally();
                sc.close();
                break;
            case 5:
                System.out.println("Watermark added");
                process = new Bitmap(inputFilePathToImage, outputFilePathToFolder, "Watermark.bmp");

                process.waterMark("add water mark");
                sc.close();
                break;
            default:
                System.out.println("Wrong entry");

        }

    }
}
